
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://SERVICE_USER
          predicates:
            - Path=/api/users/**
            - Paht=/api/auth/**
        - id: project-service
          uri: lb://SERVICE_PROJECT
          predicates:
            - Path=/api/projects/**
        - id: algorithm-service
          uri: lb:/SERVICE_ALGORITHM
          predicates:
            - Path=/api/algorithms/**
